name: 💡 Feature Request
description: Create a feature request for fastcrawler.
labels: 'enhancement'
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a feature request! Please fill out this form as completely as possible.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: A clear and concise description of what you want and what your use case is.
      placeholder: |-
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Solution Brainstorm
      description: We know you have bright ideas to share ... share away, friend.
      placeholder: |-
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏